name: CI
on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:
    types: [ labeled ]

jobs:
  prod-check:
    runs-on: self-hosted
    steps:
    
    - name: test
      run: echo "This is a test."
      
    - name: cd file
      run: Get-Content -Path C:\Users\RileyTurner\Desktop\baretest_example.txt -Tail 1
     
    - name: runner name to var
      run: echo "Deploying to production server on branch ${Env:RUNNER_NAME}"
      
      
    - name: json
      run: |
        pwd
        echo "jsonComport=$($(Get-Content .\${Env:RUNNER_NAME}.json | ConvertFrom-Json).comport)"  >> $Env:GITHUB_ENV
        
    - name: jsontwo
      run: echo "${Env:jsonComport}"
      
      
    - name: env baretest_example
      run: |
        pwd
        echo "FileContent=$(Get-Content .\baretest_example.txt)" >> $Env:GITHUB_ENV
        
    - name: baretest_example two
      run: echo "${Env:FileContents}"
      
    - name: conditional with baretest-example
      if: contains(env.FileContent, '* failed')
      run: echo "FAIL there ARE errors or failures"
      
    - name: get string fail
      run: |
        pwd
        Select-String -Path C:\Users\RileyTurner\Desktop\baretest_example.txt -Pattern '1 failed'
      
    - name: save fail as github env
      run: echo "FailContent=$(Select-String -Pattern "^(\d+) failed" -Path .\baretest_example.txt)" >> $Env:GITHUB_ENV
        
    - name: echo FailContent
      run: echo "${Env.FailContent}"
      
