name: CI
on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:
    types: [ labeled ]

jobs:
  prod-check:
    runs-on: self-hosted
    steps:
    
    - name: test
      run: echo "This is a test."
      
    - name: cd file
      run: Get-Content -Path C:\Users\RileyTurner\Desktop\baretest_example.txt -Tail 1
     
    - name: Set Variables
      run: |
      echo "Working Path: ${Env:GITHUB_WORKSPACE}"
      $branchName = $Env:GITHUB_REF -replace 'refs/heads/', ''
      echo "Branch: ${branchName}"
      echo "CURRENT_BRANCH=${branchName}" >> $Env:GITHUB_ENV

    - name: Output Variables
      run: |
      echo "${Env:CURRENT_BRANCH}"

    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        repository: 'riley-runner-test'
    ref: ${{ env.CURRENT_BRANCH }}
