name: CI
on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:
    types: [ labeled ]
    
jobs:
  prod-check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        id: checkout
        
      - name: echo message
        id: message
        run: echo "this is a test"
      
      - name: print steps
        run: |
          echo "${{steps.message.outcome}}"
