name: CI
on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:
    types: [ labeled ]

jobs:
  prod-check:
    runs-on: self-hosted
    steps:
    
    - name: test
      run: echo "This is a test."
      
    - name: cd file
      run: Get-Content -Path C:\Users\RileyTurner\Desktop\baretest_example.txt -Tail 1
     
    - name: runner name to var
      run: echo "Deploying to production server on branch ${Env:RUNNER_NAME}"
      
    - name: one
      run: echo "FileContents=$(cat ${Env:RUNNER_NAME})" >> $Env:GITHUB_ENV

    - name: onefive
      run: echo "${Env:FileContents}"
