name: CI
on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:
    types: [ labeled ]
    
jobs:
  prod-check:
    name: Run & Deploy Doxygen
    runs-on: self-hosted
    container: docker://epcpower/ccstudio9:pr3
    steps:
      - uses: actions/checkout@v2
      - name: Doxygen
        run: |
          doxygen dox/DoxyFile
          pwd
          ls
          ls html
          ls
        
